
services:
  web:
    image: eatbreads/mywebproject:latest
    ports:
      - "8088:8080"  # 将宿主机的 8080 端口映射到容器的 8080 端口
    networks:
      - mynetwork  # 使用自定义网络

  mymysql:
    image: eatbreads/mymysql:latest
    ports:
      - "3306:3306"  # 将宿主机的 3306 端口映射到容器的 3306 端口
    networks:
      - mynetwork  # 使用自定义网络

networks:
  mynetwork:
    driver: bridge  # 使用 bridge 网络模式
